import { ForecastResponse } from "../model";

export const mockForcast: ForecastResponse = {
    "cod":"200",
    "message":0,
    "cnt":40,
    "list":[
       {
          "dt":1662984000,
          "main":{
             "temp":292.97,
             "feels_like":292.39,
             "temp_min":292.94,
             "temp_max":292.97,
             "pressure":1014,
             "sea_level":1014,
             "grnd_level":950,
             "humidity":53,
             "temp_kf":0.03
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03d"
             }
          ],
          "clouds":{
             "all":41
          },
          "wind":{
             "speed":5.33,
             "deg":304,
             "gust":5.78
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-12 12:00:00"
       },
       {
          "dt":1662994800,
          "main":{
             "temp":291.7,
             "feels_like":291.02,
             "temp_min":291.06,
             "temp_max":291.7,
             "pressure":1014,
             "sea_level":1014,
             "grnd_level":950,
             "humidity":54,
             "temp_kf":0.64
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03d"
             }
          ],
          "clouds":{
             "all":45
          },
          "wind":{
             "speed":5.75,
             "deg":297,
             "gust":6.79
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-12 15:00:00"
       },
       {
          "dt":1663005600,
          "main":{
             "temp":287.22,
             "feels_like":286.48,
             "temp_min":287.22,
             "temp_max":287.22,
             "pressure":1015,
             "sea_level":1015,
             "grnd_level":950,
             "humidity":69,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03n"
             }
          ],
          "clouds":{
             "all":30
          },
          "wind":{
             "speed":2.32,
             "deg":269,
             "gust":5.23
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-12 18:00:00"
       },
       {
          "dt":1663016400,
          "main":{
             "temp":287.25,
             "feels_like":286.44,
             "temp_min":287.25,
             "temp_max":287.25,
             "pressure":1015,
             "sea_level":1015,
             "grnd_level":950,
             "humidity":66,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03n"
             }
          ],
          "clouds":{
             "all":41
          },
          "wind":{
             "speed":2.41,
             "deg":274,
             "gust":5.4
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-12 21:00:00"
       },
       {
          "dt":1663027200,
          "main":{
             "temp":287.32,
             "feels_like":286.57,
             "temp_min":287.32,
             "temp_max":287.32,
             "pressure":1014,
             "sea_level":1014,
             "grnd_level":950,
             "humidity":68,
             "temp_kf":0
          },
          "weather":[
             {
                "id":803,
                "main":"Clouds",
                "description":"broken clouds",
                "icon":"04n"
             }
          ],
          "clouds":{
             "all":55
          },
          "wind":{
             "speed":1.59,
             "deg":269,
             "gust":3.5
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-13 00:00:00"
       },
       {
          "dt":1663038000,
          "main":{
             "temp":284.72,
             "feels_like":284,
             "temp_min":284.72,
             "temp_max":284.72,
             "pressure":1014,
             "sea_level":1014,
             "grnd_level":949,
             "humidity":79,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03n"
             }
          ],
          "clouds":{
             "all":35
          },
          "wind":{
             "speed":1.72,
             "deg":277,
             "gust":2.69
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-13 03:00:00"
       },
       {
          "dt":1663048800,
          "main":{
             "temp":287.76,
             "feels_like":286.97,
             "temp_min":287.76,
             "temp_max":287.76,
             "pressure":1015,
             "sea_level":1015,
             "grnd_level":950,
             "humidity":65,
             "temp_kf":0
          },
          "weather":[
             {
                "id":801,
                "main":"Clouds",
                "description":"few clouds",
                "icon":"02d"
             }
          ],
          "clouds":{
             "all":23
          },
          "wind":{
             "speed":1.92,
             "deg":284,
             "gust":3.47
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-13 06:00:00"
       },
       {
          "dt":1663059600,
          "main":{
             "temp":292.65,
             "feels_like":291.8,
             "temp_min":292.65,
             "temp_max":292.65,
             "pressure":1014,
             "sea_level":1014,
             "grnd_level":951,
             "humidity":44,
             "temp_kf":0
          },
          "weather":[
             {
                "id":800,
                "main":"Clear",
                "description":"clear sky",
                "icon":"01d"
             }
          ],
          "clouds":{
             "all":8
          },
          "wind":{
             "speed":3.33,
             "deg":307,
             "gust":4.34
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-13 09:00:00"
       },
       {
          "dt":1663070400,
          "main":{
             "temp":294.62,
             "feels_like":293.76,
             "temp_min":294.62,
             "temp_max":294.62,
             "pressure":1012,
             "sea_level":1012,
             "grnd_level":950,
             "humidity":36,
             "temp_kf":0
          },
          "weather":[
             {
                "id":801,
                "main":"Clouds",
                "description":"few clouds",
                "icon":"02d"
             }
          ],
          "clouds":{
             "all":18
          },
          "wind":{
             "speed":3.8,
             "deg":316,
             "gust":4.62
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-13 12:00:00"
       },
       {
          "dt":1663081200,
          "main":{
             "temp":294.1,
             "feels_like":293.19,
             "temp_min":294.1,
             "temp_max":294.1,
             "pressure":1012,
             "sea_level":1012,
             "grnd_level":950,
             "humidity":36,
             "temp_kf":0
          },
          "weather":[
             {
                "id":800,
                "main":"Clear",
                "description":"clear sky",
                "icon":"01d"
             }
          ],
          "clouds":{
             "all":10
          },
          "wind":{
             "speed":3.68,
             "deg":308,
             "gust":4.93
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-13 15:00:00"
       },
       {
          "dt":1663092000,
          "main":{
             "temp":288.83,
             "feels_like":287.84,
             "temp_min":288.83,
             "temp_max":288.83,
             "pressure":1014,
             "sea_level":1014,
             "grnd_level":950,
             "humidity":53,
             "temp_kf":0
          },
          "weather":[
             {
                "id":801,
                "main":"Clouds",
                "description":"few clouds",
                "icon":"02n"
             }
          ],
          "clouds":{
             "all":17
          },
          "wind":{
             "speed":1.73,
             "deg":276,
             "gust":2.84
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-13 18:00:00"
       },
       {
          "dt":1663102800,
          "main":{
             "temp":287.41,
             "feels_like":286.41,
             "temp_min":287.41,
             "temp_max":287.41,
             "pressure":1015,
             "sea_level":1015,
             "grnd_level":951,
             "humidity":58,
             "temp_kf":0
          },
          "weather":[
             {
                "id":804,
                "main":"Clouds",
                "description":"overcast clouds",
                "icon":"04n"
             }
          ],
          "clouds":{
             "all":86
          },
          "wind":{
             "speed":0.62,
             "deg":252,
             "gust":1.08
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-13 21:00:00"
       },
       {
          "dt":1663113600,
          "main":{
             "temp":285.88,
             "feels_like":284.88,
             "temp_min":285.88,
             "temp_max":285.88,
             "pressure":1015,
             "sea_level":1015,
             "grnd_level":950,
             "humidity":64,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03n"
             }
          ],
          "clouds":{
             "all":46
          },
          "wind":{
             "speed":0.53,
             "deg":233,
             "gust":0.85
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-14 00:00:00"
       },
       {
          "dt":1663124400,
          "main":{
             "temp":285.02,
             "feels_like":283.99,
             "temp_min":285.02,
             "temp_max":285.02,
             "pressure":1016,
             "sea_level":1016,
             "grnd_level":951,
             "humidity":66,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03n"
             }
          ],
          "clouds":{
             "all":44
          },
          "wind":{
             "speed":0.73,
             "deg":267,
             "gust":0.85
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-14 03:00:00"
       },
       {
          "dt":1663135200,
          "main":{
             "temp":288.61,
             "feels_like":287.62,
             "temp_min":288.61,
             "temp_max":288.61,
             "pressure":1016,
             "sea_level":1016,
             "grnd_level":952,
             "humidity":54,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03d"
             }
          ],
          "clouds":{
             "all":28
          },
          "wind":{
             "speed":0.84,
             "deg":263,
             "gust":1.44
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-14 06:00:00"
       },
       {
          "dt":1663146000,
          "main":{
             "temp":295.96,
             "feels_like":295.18,
             "temp_min":295.96,
             "temp_max":295.96,
             "pressure":1015,
             "sea_level":1015,
             "grnd_level":952,
             "humidity":34,
             "temp_kf":0
          },
          "weather":[
             {
                "id":801,
                "main":"Clouds",
                "description":"few clouds",
                "icon":"02d"
             }
          ],
          "clouds":{
             "all":12
          },
          "wind":{
             "speed":2.01,
             "deg":276,
             "gust":3.4
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-14 09:00:00"
       },
       {
          "dt":1663156800,
          "main":{
             "temp":300.17,
             "feels_like":299.4,
             "temp_min":300.17,
             "temp_max":300.17,
             "pressure":1013,
             "sea_level":1013,
             "grnd_level":951,
             "humidity":25,
             "temp_kf":0
          },
          "weather":[
             {
                "id":800,
                "main":"Clear",
                "description":"clear sky",
                "icon":"01d"
             }
          ],
          "clouds":{
             "all":10
          },
          "wind":{
             "speed":2.54,
             "deg":262,
             "gust":3.9
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-14 12:00:00"
       },
       {
          "dt":1663167600,
          "main":{
             "temp":300.38,
             "feels_like":299.72,
             "temp_min":300.38,
             "temp_max":300.38,
             "pressure":1011,
             "sea_level":1011,
             "grnd_level":950,
             "humidity":30,
             "temp_kf":0
          },
          "weather":[
             {
                "id":800,
                "main":"Clear",
                "description":"clear sky",
                "icon":"01d"
             }
          ],
          "clouds":{
             "all":6
          },
          "wind":{
             "speed":1.56,
             "deg":234,
             "gust":3.23
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-14 15:00:00"
       },
       {
          "dt":1663178400,
          "main":{
             "temp":293.23,
             "feels_like":292.39,
             "temp_min":293.23,
             "temp_max":293.23,
             "pressure":1013,
             "sea_level":1013,
             "grnd_level":950,
             "humidity":42,
             "temp_kf":0
          },
          "weather":[
             {
                "id":801,
                "main":"Clouds",
                "description":"few clouds",
                "icon":"02n"
             }
          ],
          "clouds":{
             "all":12
          },
          "wind":{
             "speed":0.81,
             "deg":206,
             "gust":1.45
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-14 18:00:00"
       },
       {
          "dt":1663189200,
          "main":{
             "temp":291.4,
             "feels_like":290.43,
             "temp_min":291.4,
             "temp_max":291.4,
             "pressure":1014,
             "sea_level":1014,
             "grnd_level":950,
             "humidity":44,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03n"
             }
          ],
          "clouds":{
             "all":38
          },
          "wind":{
             "speed":0.68,
             "deg":215,
             "gust":1.17
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-14 21:00:00"
       },
       {
          "dt":1663200000,
          "main":{
             "temp":290.11,
             "feels_like":289.09,
             "temp_min":290.11,
             "temp_max":290.11,
             "pressure":1014,
             "sea_level":1014,
             "grnd_level":950,
             "humidity":47,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03n"
             }
          ],
          "clouds":{
             "all":31
          },
          "wind":{
             "speed":0.93,
             "deg":253,
             "gust":1.1
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-15 00:00:00"
       },
       {
          "dt":1663210800,
          "main":{
             "temp":289.4,
             "feels_like":288.33,
             "temp_min":289.4,
             "temp_max":289.4,
             "pressure":1013,
             "sea_level":1013,
             "grnd_level":949,
             "humidity":48,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03n"
             }
          ],
          "clouds":{
             "all":33
          },
          "wind":{
             "speed":0.79,
             "deg":246,
             "gust":1.03
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-15 03:00:00"
       },
       {
          "dt":1663221600,
          "main":{
             "temp":292.85,
             "feels_like":291.97,
             "temp_min":292.85,
             "temp_max":292.85,
             "pressure":1013,
             "sea_level":1013,
             "grnd_level":950,
             "humidity":42,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03d"
             }
          ],
          "clouds":{
             "all":25
          },
          "wind":{
             "speed":0.71,
             "deg":251,
             "gust":1.3
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-15 06:00:00"
       },
       {
          "dt":1663232400,
          "main":{
             "temp":300.97,
             "feels_like":299.99,
             "temp_min":300.97,
             "temp_max":300.97,
             "pressure":1011,
             "sea_level":1011,
             "grnd_level":950,
             "humidity":27,
             "temp_kf":0
          },
          "weather":[
             {
                "id":804,
                "main":"Clouds",
                "description":"overcast clouds",
                "icon":"04d"
             }
          ],
          "clouds":{
             "all":86
          },
          "wind":{
             "speed":1.93,
             "deg":242,
             "gust":4.96
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-15 09:00:00"
       },
       {
          "dt":1663243200,
          "main":{
             "temp":306.02,
             "feels_like":304.03,
             "temp_min":306.02,
             "temp_max":306.02,
             "pressure":1009,
             "sea_level":1009,
             "grnd_level":948,
             "humidity":21,
             "temp_kf":0
          },
          "weather":[
             {
                "id":803,
                "main":"Clouds",
                "description":"broken clouds",
                "icon":"04d"
             }
          ],
          "clouds":{
             "all":83
          },
          "wind":{
             "speed":4.36,
             "deg":245,
             "gust":11.23
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-15 12:00:00"
       },
       {
          "dt":1663254000,
          "main":{
             "temp":303.33,
             "feels_like":301.93,
             "temp_min":303.33,
             "temp_max":303.33,
             "pressure":1009,
             "sea_level":1009,
             "grnd_level":948,
             "humidity":28,
             "temp_kf":0
          },
          "weather":[
             {
                "id":804,
                "main":"Clouds",
                "description":"overcast clouds",
                "icon":"04d"
             }
          ],
          "clouds":{
             "all":87
          },
          "wind":{
             "speed":5.2,
             "deg":275,
             "gust":10.36
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-15 15:00:00"
       },
       {
          "dt":1663264800,
          "main":{
             "temp":296.93,
             "feels_like":296.43,
             "temp_min":296.93,
             "temp_max":296.93,
             "pressure":1011,
             "sea_level":1011,
             "grnd_level":949,
             "humidity":41,
             "temp_kf":0
          },
          "weather":[
             {
                "id":803,
                "main":"Clouds",
                "description":"broken clouds",
                "icon":"04n"
             }
          ],
          "clouds":{
             "all":72
          },
          "wind":{
             "speed":2.19,
             "deg":267,
             "gust":5.55
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-15 18:00:00"
       },
       {
          "dt":1663275600,
          "main":{
             "temp":295.6,
             "feels_like":295.05,
             "temp_min":295.6,
             "temp_max":295.6,
             "pressure":1011,
             "sea_level":1011,
             "grnd_level":949,
             "humidity":44,
             "temp_kf":0
          },
          "weather":[
             {
                "id":803,
                "main":"Clouds",
                "description":"broken clouds",
                "icon":"04n"
             }
          ],
          "clouds":{
             "all":81
          },
          "wind":{
             "speed":1.26,
             "deg":260,
             "gust":4.52
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-15 21:00:00"
       },
       {
          "dt":1663286400,
          "main":{
             "temp":293.28,
             "feels_like":292.68,
             "temp_min":293.28,
             "temp_max":293.28,
             "pressure":1011,
             "sea_level":1011,
             "grnd_level":948,
             "humidity":51,
             "temp_kf":0
          },
          "weather":[
             {
                "id":803,
                "main":"Clouds",
                "description":"broken clouds",
                "icon":"04n"
             }
          ],
          "clouds":{
             "all":82
          },
          "wind":{
             "speed":0.52,
             "deg":228,
             "gust":1.16
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-16 00:00:00"
       },
       {
          "dt":1663297200,
          "main":{
             "temp":291.97,
             "feels_like":291.37,
             "temp_min":291.97,
             "temp_max":291.97,
             "pressure":1011,
             "sea_level":1011,
             "grnd_level":948,
             "humidity":56,
             "temp_kf":0
          },
          "weather":[
             {
                "id":803,
                "main":"Clouds",
                "description":"broken clouds",
                "icon":"04n"
             }
          ],
          "clouds":{
             "all":57
          },
          "wind":{
             "speed":1.73,
             "deg":271,
             "gust":1.99
          },
          "visibility":10000,
          "pop":0.05,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-16 03:00:00"
       },
       {
          "dt":1663308000,
          "main":{
             "temp":294.45,
             "feels_like":293.99,
             "temp_min":294.45,
             "temp_max":294.45,
             "pressure":1011,
             "sea_level":1011,
             "grnd_level":948,
             "humidity":52,
             "temp_kf":0
          },
          "weather":[
             {
                "id":803,
                "main":"Clouds",
                "description":"broken clouds",
                "icon":"04d"
             }
          ],
          "clouds":{
             "all":76
          },
          "wind":{
             "speed":0.27,
             "deg":293,
             "gust":1.32
          },
          "visibility":10000,
          "pop":0.06,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-16 06:00:00"
       },
       {
          "dt":1663318800,
          "main":{
             "temp":301.32,
             "feels_like":300.52,
             "temp_min":301.32,
             "temp_max":301.32,
             "pressure":1009,
             "sea_level":1009,
             "grnd_level":948,
             "humidity":33,
             "temp_kf":0
          },
          "weather":[
             {
                "id":804,
                "main":"Clouds",
                "description":"overcast clouds",
                "icon":"04d"
             }
          ],
          "clouds":{
             "all":96
          },
          "wind":{
             "speed":1.79,
             "deg":252,
             "gust":4.86
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-16 09:00:00"
       },
       {
          "dt":1663329600,
          "main":{
             "temp":301.86,
             "feels_like":301.02,
             "temp_min":301.86,
             "temp_max":301.86,
             "pressure":1008,
             "sea_level":1008,
             "grnd_level":947,
             "humidity":34,
             "temp_kf":0
          },
          "weather":[
             {
                "id":804,
                "main":"Clouds",
                "description":"overcast clouds",
                "icon":"04d"
             }
          ],
          "clouds":{
             "all":97
          },
          "wind":{
             "speed":6.84,
             "deg":279,
             "gust":10.72
          },
          "visibility":10000,
          "pop":0.05,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-16 12:00:00"
       },
       {
          "dt":1663340400,
          "main":{
             "temp":298.12,
             "feels_like":297.98,
             "temp_min":298.12,
             "temp_max":298.12,
             "pressure":1009,
             "sea_level":1009,
             "grnd_level":947,
             "humidity":50,
             "temp_kf":0
          },
          "weather":[
             {
                "id":804,
                "main":"Clouds",
                "description":"overcast clouds",
                "icon":"04d"
             }
          ],
          "clouds":{
             "all":97
          },
          "wind":{
             "speed":3.51,
             "deg":285,
             "gust":7.91
          },
          "visibility":10000,
          "pop":0.37,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-16 15:00:00"
       },
       {
          "dt":1663351200,
          "main":{
             "temp":295.81,
             "feels_like":295.62,
             "temp_min":295.81,
             "temp_max":295.81,
             "pressure":1008,
             "sea_level":1008,
             "grnd_level":946,
             "humidity":57,
             "temp_kf":0
          },
          "weather":[
             {
                "id":804,
                "main":"Clouds",
                "description":"overcast clouds",
                "icon":"04n"
             }
          ],
          "clouds":{
             "all":95
          },
          "wind":{
             "speed":2.61,
             "deg":247,
             "gust":5.72
          },
          "visibility":10000,
          "pop":0.27,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-16 18:00:00"
       },
       {
          "dt":1663362000,
          "main":{
             "temp":293.57,
             "feels_like":293.34,
             "temp_min":293.57,
             "temp_max":293.57,
             "pressure":1008,
             "sea_level":1008,
             "grnd_level":945,
             "humidity":64,
             "temp_kf":0
          },
          "weather":[
             {
                "id":500,
                "main":"Rain",
                "description":"light rain",
                "icon":"10n"
             }
          ],
          "clouds":{
             "all":100
          },
          "wind":{
             "speed":0.63,
             "deg":180,
             "gust":1.25
          },
          "visibility":10000,
          "pop":0.21,
          "rain":{
             "3h":0.11
          },
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-16 21:00:00"
       },
       {
          "dt":1663372800,
          "main":{
             "temp":292.27,
             "feels_like":291.99,
             "temp_min":292.27,
             "temp_max":292.27,
             "pressure":1007,
             "sea_level":1007,
             "grnd_level":944,
             "humidity":67,
             "temp_kf":0
          },
          "weather":[
             {
                "id":804,
                "main":"Clouds",
                "description":"overcast clouds",
                "icon":"04n"
             }
          ],
          "clouds":{
             "all":98
          },
          "wind":{
             "speed":0.2,
             "deg":283,
             "gust":0.43
          },
          "visibility":10000,
          "pop":0.05,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-17 00:00:00"
       },
       {
          "dt":1663383600,
          "main":{
             "temp":291.84,
             "feels_like":291.64,
             "temp_min":291.84,
             "temp_max":291.84,
             "pressure":1006,
             "sea_level":1006,
             "grnd_level":943,
             "humidity":72,
             "temp_kf":0
          },
          "weather":[
             {
                "id":804,
                "main":"Clouds",
                "description":"overcast clouds",
                "icon":"04n"
             }
          ],
          "clouds":{
             "all":100
          },
          "wind":{
             "speed":1.74,
             "deg":304,
             "gust":2.21
          },
          "visibility":10000,
          "pop":0.25,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2022-09-17 03:00:00"
       },
       {
          "dt":1663394400,
          "main":{
             "temp":291.08,
             "feels_like":291.2,
             "temp_min":291.08,
             "temp_max":291.08,
             "pressure":1006,
             "sea_level":1006,
             "grnd_level":943,
             "humidity":87,
             "temp_kf":0
          },
          "weather":[
             {
                "id":500,
                "main":"Rain",
                "description":"light rain",
                "icon":"10d"
             }
          ],
          "clouds":{
             "all":100
          },
          "wind":{
             "speed":0.67,
             "deg":134,
             "gust":1.45
          },
          "visibility":10000,
          "pop":0.67,
          "rain":{
             "3h":2.73
          },
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-17 06:00:00"
       },
       {
          "dt":1663405200,
          "main":{
             "temp":294.8,
             "feels_like":294.85,
             "temp_min":294.8,
             "temp_max":294.8,
             "pressure":1006,
             "sea_level":1006,
             "grnd_level":943,
             "humidity":70,
             "temp_kf":0
          },
          "weather":[
             {
                "id":500,
                "main":"Rain",
                "description":"light rain",
                "icon":"10d"
             }
          ],
          "clouds":{
             "all":94
          },
          "wind":{
             "speed":1.13,
             "deg":314,
             "gust":3.4
          },
          "visibility":10000,
          "pop":0.45,
          "rain":{
             "3h":0.52
          },
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2022-09-17 09:00:00"
       }
    ],
    "city":{
       "id":727011,
       "name":"Sofia",
       "coord":{
          "lat":42.6975,
          "lon":23.3242
       },
       "country":"BG",
       "population":1152556,
       "timezone":10800,
       "sunrise":1662955383,
       "sunset":1663001004
    }
 }